version: '3.8'

services:
  postgres_test:
    image: postgres:15
    container_name: postgres_test
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
  api_notetools:
    image: api-notetools:2.0.1
    env_file:
      - .env
    container_name: api-notetools
    restart: always
    ports:
      - "3333:3333"

volumes:
  postgres_test_data:
  api_notetools:

